name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install -DskipTests -pl  nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core -am
        run: mvn -pl nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core test -Dtest=org.apache.nifi.controller.status.history.EmbeddedQuestDbStatusHistoryRepositoryForComponentsTest#testReadingLimitedByPreferredDataPoints
  
